#!/usr/bin/env zsh

NEW=$(notmuch count -- tag:new and not tag:sent)

if [[ $NEW -gt 0 ]]; then
    echo "classify"
    $MAIL_DIR/.notmuch/hooks/classify classify tag:new
    echo "refile"
    CHANGED=("${(@f)$($MAIL_DIR/.notmuch/hooks/refile)}")

    SUB=$(notmuch search --format=json -- tag:new and not tag:sent |
              jq -j '.[0:5]|.[]|.subject+"\n"')

    notmuch tag -new -- tag:new

    # if the refiler changed some stuff, we should probably sync again
    if [[ $#CHANGED -gt 1 ]]; then
        echo "$#CHANGED" "$CHANGED"
        mbsync -q $CHANGED 2>&1
        ## DANGER WILL ROBINSON
        notmuch new
    fi

    if [ $NEW -ne 0 ]
    then
        notify "$NEW new mails" "$SUB"
    fi
fi

if [ x$DISPLAY != x ]; then
    xprop -f UNREAD_EMAILS 8s -set UNREAD_EMAILS $(notmuch count tag:unread) -root
fi
