#!/usr/bin/env zsh

NEW=$(notmuch count -- tag:new and not from:tom.hinton@cse.org.uk and not from:larkery.com)
SUB=$(notmuch search --format=json -- tag:new and not from:me | jq -j '.[0:5]|.[]|.subject+"\n"')
echo "classifying new mail..."
$MAIL_DIR/.notmuch/hooks/classify --tag tag:new
echo "refiling new mail..."
CHANGED=("${(@f)$($MAIL_DIR/.notmuch/hooks/refile)}")
notmuch tag -new -- tag:new

if [ ! "$?" -eq 0 ]
then
    echo "ERROR: refiler was not happy"
fi

# if the refiler changed some stuff, we should probably sync again
if [[ $#CHANGED -gt 1 ]]; then
    echo $#CHANGED "$CHANGED"
    mbsync -q $CHANGED 2>&1
fi

if [ $NEW -ne 0 ]
then
    notify "$NEW new mails" "$SUB"
fi

if [ x$DISPLAY != x ]; then
    xprop -f UNREAD_EMAILS 8s -set UNREAD_EMAILS $(notmuch count tag:unread) -root
fi
