#!/usr/bin/env zsh

NEW=$(notmuch count -- tag:new and not from:tom.hinton@cse.org.uk and not from:larkery.com)
SUB=$(notmuch search --format=json -- tag:new and not from:me | jq -j '.[0:5]|.[]|.subject+"\n"')
notmuch tag -new -- tag:new

CHANGED=("${(@f)$($MAIL_DIR/.notmuch/hooks/refile)}")

if [ ! "$?" -eq 0 ]
then
    echo "ERROR: refiler was not happy"
fi

# if the refiler changed some stuff, we should probably sync again
if [[ $#CHANGED -gt 1 ]]; then
    echo $#CHANGED "$CHANGED"
    mbsync -q $CHANGED 2>&1
fi

if [ $NEW -ne 0 ]
then
    notify "$NEW new mails" "$SUB"
    if [ -S /tmp/emacs${UID}/server ]; then
        emacsclient -n -e '(notmuch-refresh-all-buffers)'
    fi
fi
