#!/usr/bin/env zsh

CHANGED=("${(@f)$($MAIL_DIR/.notmuch/hooks/refile)}")
CHANGED+=(fastmail-inbox:INBOX)
CHANGED+=(cse:Inbox)
typeset -U CHANGED

if [ ! "$?" -eq 0 ]
then
    echo "ERROR: refiler was not happy"
fi

WATCH="$MAIL_DIR/last-sync"

if [[ -z "$NO_SYNC" ]]; then
    if [[ -n "$FULL" ]] || [[ ! -e "$WATCH" ]] || [[ $(date +%s -r "$WATCH") -lt $(date +%s --date="3 hours ago") ]]
    then
        echo "check all mail"
        FULL=1
        # also delete duplicates
        E=$(pmbsync 2>&1)
    else
        echo check "$CHANGED"
        E=$(pmbsync $CHANGED 2>&1)
    fi
fi


if [ ! "$?" -eq 0 ]
then
    echo "$E" >&2
    notify-send -u critical -t 0 "Mail Errors"
else
    [[ -n "$FULL" ]] && touch "$WATCH"
fi

if [[ -n "$VERBOSE" ]]; then
    echo "$E"
fi
